version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install dependencies
      - run:
          name: Installing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: repo

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      # run linter
      - run:
          name: Linting
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/

      # run tests
      - run:
          name: Running tests
          command: yarn test && yarn codecov

workflows:
  version: 2
  test:
    jobs:
      - build

      - lint:
          requires:
            - build

      - test:
          requires:
            - build
